name: Javascript Quality Checks

on:
  pull_request:
  push:
    branches:
      - main

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  checks:
    name: Lint JS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install npm dependencies
        run: yarn install --frozen-lockfile

      - name: Run wp-script lint:js on src folder
        run: yarn run lint:js src

      - name: Check for version number consistency
        run: node check_versions.js
